services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/media:/media
    devices:
      - /dev/dri:/dev/dri     # Intel iGPU
    ports:
      - 8096:8096             # HTTP
      # - 8920:8920           # HTTPS
    restart: unless-stopped
