services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - "3001:3001"  # Change host port if needed
    volumes:
      - ./uptime-kuma:/app/data
